### ISSUE TITLE
Move recommonmark-0.4.0-py_0 to broken

### ISSUE THREAD

**Issue by dopplershift** [conda-forge/recommonmark-feedstock#3]
Can somebody move the recommonmark-0.4.0-py_0 packges to the Broken label? They didn’t list a version limit on commonmark, and now conda wants to downgrade to it so that it can upgrade my commonmark—which would break my env.

**Comment by jakirkham** [comment]
Thoughts, @conda-forge/core?

**Comment by scopatz** [comment]
I am not opposed.

**Comment by CJ-Wright** [comment]
Not opposed either, can we get a PR which pins?

**Comment by dopplershift** [comment]
#1 pinned already...unless I misunderstand you?

**Comment by CJ-Wright** [comment]
Awesome, sorry I didn't see that :sheep:

**Comment by jakirkham** [comment]
Ok, went ahead and did it. Hope that helps.

**Comment by dopplershift** [comment]
That took care of it. Thanks!
